# Generated by Django 5.0.6 on 2026-09-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('mahindi_required', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('mahindi_submitted', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mahindi_debt', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mboga_required', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('mboga_submitted', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mboga_debt', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cash_required', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('cash_submitted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('HAS_DEBT', 'Has Debt'), ('COMPLETED', 'Completed')], default='HAS_DEBT', max_length=15)),
                ('sms_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=15)),
                ('recorded_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='students.student')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('student', 'month', 'year'), name='unique_student_month_year'),
        ),
    ]
