# Generated by Django 5.0.6 on 2026-09-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('DEBT_REMINDER', 'Debt Reminder'), ('COMPLETION', 'Completion'), ('CUSTOM', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
