# Generated by Django 5.0.6 on 2026-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.TextField(help_text='Use placeholders: {guardian}, {student}, {month}, {year}, {debt_items}')),
                ('type', models.CharField(choices=[('DEBT_REMINDER', 'Debt Reminder'), ('COMPLETION', 'Completion'), ('CUSTOM', 'Custom')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='MKALAPA SECONDARY SCHOOL', max_length=200)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
                ('school_address', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(default='MKALAPA', max_length=20)),
                ('mahindi_requirement', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('mboga_requirement', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('cash_requirement', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
